"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-28 01:43:40.404598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imprezy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('klient', sa.String(length=128), nullable=False),
    sa.Column('liczba_osob', sa.Integer(), nullable=True),
    sa.Column('godzina', sa.String(length=32), nullable=True),
    sa.Column('sala', sa.String(length=16), nullable=True),
    sa.Column('sciezka_pliku', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sciezka_pliku')
    )
    with op.batch_alter_table('imprezy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imprezy_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_imprezy_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imprezy_klient'), ['klient'], unique=False)

    op.create_table('pracownicy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imie', sa.String(length=64), nullable=False),
    sa.Column('nazwisko', sa.String(length=64), nullable=False),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('kolejnosc', sa.Integer(), nullable=False),
    sa.Column('kolor', sa.String(length=16), nullable=True),
    sa.Column('dzial', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pracownicy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pracownicy_id'), ['id'], unique=False)

    op.create_table('publikacje_grafiku',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('koniec', sa.Date(), nullable=False),
    sa.Column('opublikowano_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start', 'koniec')
    )
    with op.batch_alter_table('publikacje_grafiku', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publikacje_grafiku_id'), ['id'], unique=False)

    op.create_table('rozliczenia_dnia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('zadatek', sa.Float(), nullable=False),
    sa.Column('zadatek_gotowka', sa.Float(), nullable=False),
    sa.Column('zadatek_karta', sa.Float(), nullable=False),
    sa.Column('imp_reczny', sa.Boolean(), nullable=False),
    sa.Column('imp_gotowka', sa.Float(), nullable=False),
    sa.Column('imp_karta', sa.Float(), nullable=False),
    sa.Column('przelew', sa.Float(), nullable=False),
    sa.Column('terminale', sa.JSON(), nullable=True),
    sa.Column('kasy', sa.JSON(), nullable=True),
    sa.Column('utworzono_at', sa.DateTime(), nullable=True),
    sa.Column('przekazano_szef_at', sa.DateTime(), nullable=True),
    sa.Column('push_admin_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rozliczenia_dnia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rozliczenia_dnia_data'), ['data'], unique=True)
        batch_op.create_index(batch_op.f('ix_rozliczenia_dnia_id'), ['id'], unique=False)

    op.create_table('sprzatanie_korekty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('sala', sa.String(length=32), nullable=False),
    sa.Column('akcja', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'sala')
    )
    with op.batch_alter_table('sprzatanie_korekty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprzatanie_korekty_id'), ['id'], unique=False)

    op.create_table('stan_stolow',
    sa.Column('rewir_nr', sa.Integer(), nullable=False),
    sa.Column('otwarte', sa.Integer(), nullable=False),
    sa.Column('zaktualizowano_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rewir_nr')
    )
    op.create_table('stanowiska',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('tylko_weekend', sa.Boolean(), nullable=True),
    sa.Column('widoczny_dla_wszystkich', sa.Boolean(), nullable=False),
    sa.Column('grupa_widocznosci', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    with op.batch_alter_table('stanowiska', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stanowiska_id'), ['id'], unique=False)

    op.create_table('stoliki_historia',
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('liczba', sa.Integer(), nullable=False),
    sa.Column('zaktualizowano_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('data')
    )
    op.create_table('terminy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nazwisko', sa.String(), nullable=False),
    sa.Column('typ', sa.String(length=32), nullable=True),
    sa.Column('liczba_osob', sa.Integer(), nullable=True),
    sa.Column('telefon', sa.String(length=32), nullable=True),
    sa.Column('sala', sa.String(length=64), nullable=True),
    sa.Column('notatka', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('zadatek', sa.Float(), nullable=False),
    sa.Column('utworzono_at', sa.DateTime(), nullable=True),
    sa.Column('ical_uid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminy_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminy_ical_uid'), ['ical_uid'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminy_id'), ['id'], unique=False)

    op.create_table('zeszyt_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stan_poczatkowy', sa.Float(), nullable=False),
    sa.Column('stan_poczatkowy_data', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zeszyt_pozycje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('kolumna', sa.String(length=16), nullable=False),
    sa.Column('opis', sa.String(), nullable=True),
    sa.Column('kwota', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zeszyt_pozycje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zeszyt_pozycje_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_zeszyt_pozycje_id'), ['id'], unique=False)

    op.create_table('zeszyt_przychody',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('zrodlo', sa.String(), nullable=True),
    sa.Column('gotowka', sa.Float(), nullable=False),
    sa.Column('terminal', sa.Float(), nullable=False),
    sa.Column('przelew', sa.Float(), nullable=False),
    sa.Column('impreza', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zeszyt_przychody', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zeszyt_przychody_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_zeszyt_przychody_id'), ['id'], unique=False)

    op.create_table('dyspozycje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('dostepnosc', sa.Boolean(), nullable=False),
    sa.Column('godz_od', sa.Time(), nullable=True),
    sa.Column('godz_do', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pracownik_id', 'data')
    )
    with op.batch_alter_table('dyspozycje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dyspozycje_id'), ['id'], unique=False)

    op.create_table('kp_zadatki',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('numer', sa.String(length=64), nullable=True),
    sa.Column('kwota', sa.Float(), nullable=False),
    sa.Column('opis', sa.String(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nazwisko', sa.String(), nullable=True),
    sa.Column('data_imprezy', sa.Date(), nullable=True),
    sa.Column('termin_id', sa.Integer(), nullable=True),
    sa.Column('zaktualizowano_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['termin_id'], ['terminy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kp_zadatki', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kp_zadatki_data'), ['data'], unique=False)

    op.create_table('odbicia_rcp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rcp_id', sa.String(length=128), nullable=False),
    sa.Column('imie_nazwisko', sa.String(length=128), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('wejscie', sa.DateTime(), nullable=True),
    sa.Column('wyjscie', sa.DateTime(), nullable=True),
    sa.Column('godziny', sa.Float(), nullable=True),
    sa.Column('powiadomiono_wejscie', sa.Boolean(), nullable=True),
    sa.Column('powiadomiono_wyjscie', sa.Boolean(), nullable=True),
    sa.Column('zaktualizowano_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('odbicia_rcp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_odbicia_rcp_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_odbicia_rcp_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odbicia_rcp_pracownik_id'), ['pracownik_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_odbicia_rcp_rcp_id'), ['rcp_id'], unique=True)

    op.create_table('podkategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(length=64), nullable=False),
    sa.Column('godz_od', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('podkategorie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_podkategorie_id'), ['id'], unique=False)

    op.create_table('pracownik_stanowisko',
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ),
    sa.PrimaryKeyConstraint('pracownik_id', 'stanowisko_id')
    )
    op.create_table('przydzialy_zmian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('godz_od', sa.Time(), nullable=True),
    sa.Column('rewir', sa.String(), nullable=True),
    sa.Column('zamyka', sa.Boolean(), nullable=False),
    sa.Column('zamyka_reczny', sa.Boolean(), nullable=False),
    sa.Column('zamyka_rewir', sa.Boolean(), nullable=False),
    sa.Column('rozlicza_imprize', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'stanowisko_id', 'pracownik_id', 'godz_od')
    )
    with op.batch_alter_table('przydzialy_zmian', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_przydzialy_zmian_id'), ['id'], unique=False)

    op.create_table('rozliczenia_dnia_kelnerzy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rozliczenie_id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('gotowka', sa.Float(), nullable=False),
    sa.Column('karta', sa.Float(), nullable=False),
    sa.Column('fv', sa.Float(), nullable=False),
    sa.Column('kp', sa.Float(), nullable=False),
    sa.Column('kp_zadatek', sa.Boolean(), nullable=False),
    sa.Column('kw', sa.Float(), nullable=False),
    sa.Column('potwierdzone', sa.Boolean(), nullable=False),
    sa.Column('push_oczekuje_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.ForeignKeyConstraint(['rozliczenie_id'], ['rozliczenia_dnia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rozliczenia_dnia_kelnerzy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rozliczenia_dnia_kelnerzy_id'), ['id'], unique=False)

    op.create_table('rozliczenia_gastro',
    sa.Column('poz_id', sa.String(length=36), nullable=False),
    sa.Column('rozliczenie_id', sa.String(length=36), nullable=False),
    sa.Column('imie_nazwisko', sa.String(length=128), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('zamknieto', sa.DateTime(), nullable=True),
    sa.Column('zamkniete', sa.Boolean(), nullable=False),
    sa.Column('forma', sa.String(length=64), nullable=False),
    sa.Column('sprzedaz', sa.Float(), nullable=False),
    sa.Column('deklarowane', sa.Float(), nullable=False),
    sa.Column('powiadomiono', sa.Boolean(), nullable=False),
    sa.Column('zaktualizowano_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('poz_id')
    )
    with op.batch_alter_table('rozliczenia_gastro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rozliczenia_gastro_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_rozliczenia_gastro_rozliczenie_id'), ['rozliczenie_id'], unique=False)

    op.create_table('rozliczenia_imprez',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(), nullable=True),
    sa.Column('utworzono_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rozliczenia_imprez', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rozliczenia_imprez_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_rozliczenia_imprez_id'), ['id'], unique=False)

    op.create_table('sprzatanie_odhaczenia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('sala', sa.String(length=32), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=True),
    sa.Column('odhaczono_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'sala')
    )
    with op.batch_alter_table('sprzatanie_odhaczenia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprzatanie_odhaczenia_id'), ['id'], unique=False)

    op.create_table('stawki_pracownikow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.Column('stawka', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pracownik_id', 'stanowisko_id')
    )
    with op.batch_alter_table('stawki_pracownikow', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stawki_pracownikow_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stawki_pracownikow_pracownik_id'), ['pracownik_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stawki_pracownikow_stanowisko_id'), ['stanowisko_id'], unique=False)

    op.create_table('urlopy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('koniec', sa.Date(), nullable=False),
    sa.Column('powod', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('utworzono_at', sa.DateTime(), nullable=False),
    sa.Column('rozpatrzono_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('urlopy', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_urlopy_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('haslo_hash', sa.String(length=255), nullable=False),
    sa.Column('rola', sa.String(length=16), nullable=False),
    sa.Column('aktywny', sa.Boolean(), nullable=True),
    sa.Column('pracownik_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pracownik_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_login'), ['login'], unique=True)

    op.create_table('wymagania_dnia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('stanowisko_id', sa.Integer(), nullable=False),
    sa.Column('godz_od', sa.Time(), nullable=True),
    sa.Column('rewir', sa.String(), nullable=True),
    sa.Column('liczba_osob', sa.Integer(), nullable=True),
    sa.Column('jest_impreza', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stanowisko_id'], ['stanowiska.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wymagania_dnia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wymagania_dnia_id'), ['id'], unique=False)

    op.create_table('zamowienia_sprzataczki',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pracownik_id', sa.Integer(), nullable=False),
    sa.Column('utworzono_at', sa.DateTime(), nullable=False),
    sa.Column('nazwa', sa.String(length=128), nullable=False),
    sa.Column('ilosc', sa.String(length=64), nullable=True),
    sa.Column('notatka', sa.String(), nullable=True),
    sa.Column('zdjecie', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('odczytano_at', sa.DateTime(), nullable=True),
    sa.Column('zamowiono_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pracownik_id'], ['pracownicy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zamowienia_sprzataczki', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zamowienia_sprzataczki_id'), ['id'], unique=False)

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh', sa.String(), nullable=False),
    sa.Column('auth', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_push_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('rozliczenia_imprez_pozycje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rozliczenie_id', sa.Integer(), nullable=False),
    sa.Column('forma', sa.String(length=16), nullable=False),
    sa.Column('kwota', sa.Float(), nullable=False),
    sa.Column('sfiskalizowane', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rozliczenie_id'], ['rozliczenia_imprez.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rozliczenia_imprez_pozycje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rozliczenia_imprez_pozycje_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rozliczenia_imprez_pozycje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rozliczenia_imprez_pozycje_id'))

    op.drop_table('rozliczenia_imprez_pozycje')
    with op.batch_alter_table('push_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_push_subscriptions_id'))

    op.drop_table('push_subscriptions')
    with op.batch_alter_table('zamowienia_sprzataczki', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zamowienia_sprzataczki_id'))

    op.drop_table('zamowienia_sprzataczki')
    with op.batch_alter_table('wymagania_dnia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wymagania_dnia_id'))

    op.drop_table('wymagania_dnia')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_login'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('urlopy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_urlopy_id'))

    op.drop_table('urlopy')
    with op.batch_alter_table('stawki_pracownikow', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stawki_pracownikow_stanowisko_id'))
        batch_op.drop_index(batch_op.f('ix_stawki_pracownikow_pracownik_id'))
        batch_op.drop_index(batch_op.f('ix_stawki_pracownikow_id'))

    op.drop_table('stawki_pracownikow')
    with op.batch_alter_table('sprzatanie_odhaczenia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprzatanie_odhaczenia_id'))

    op.drop_table('sprzatanie_odhaczenia')
    with op.batch_alter_table('rozliczenia_imprez', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rozliczenia_imprez_id'))
        batch_op.drop_index(batch_op.f('ix_rozliczenia_imprez_data'))

    op.drop_table('rozliczenia_imprez')
    with op.batch_alter_table('rozliczenia_gastro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rozliczenia_gastro_rozliczenie_id'))
        batch_op.drop_index(batch_op.f('ix_rozliczenia_gastro_data'))

    op.drop_table('rozliczenia_gastro')
    with op.batch_alter_table('rozliczenia_dnia_kelnerzy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rozliczenia_dnia_kelnerzy_id'))

    op.drop_table('rozliczenia_dnia_kelnerzy')
    with op.batch_alter_table('przydzialy_zmian', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_przydzialy_zmian_id'))

    op.drop_table('przydzialy_zmian')
    op.drop_table('pracownik_stanowisko')
    with op.batch_alter_table('podkategorie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podkategorie_id'))

    op.drop_table('podkategorie')
    with op.batch_alter_table('odbicia_rcp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_odbicia_rcp_rcp_id'))
        batch_op.drop_index(batch_op.f('ix_odbicia_rcp_pracownik_id'))
        batch_op.drop_index(batch_op.f('ix_odbicia_rcp_id'))
        batch_op.drop_index(batch_op.f('ix_odbicia_rcp_data'))

    op.drop_table('odbicia_rcp')
    with op.batch_alter_table('kp_zadatki', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kp_zadatki_data'))

    op.drop_table('kp_zadatki')
    with op.batch_alter_table('dyspozycje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dyspozycje_id'))

    op.drop_table('dyspozycje')
    with op.batch_alter_table('zeszyt_przychody', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zeszyt_przychody_id'))
        batch_op.drop_index(batch_op.f('ix_zeszyt_przychody_data'))

    op.drop_table('zeszyt_przychody')
    with op.batch_alter_table('zeszyt_pozycje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zeszyt_pozycje_id'))
        batch_op.drop_index(batch_op.f('ix_zeszyt_pozycje_data'))

    op.drop_table('zeszyt_pozycje')
    op.drop_table('zeszyt_config')
    with op.batch_alter_table('terminy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminy_id'))
        batch_op.drop_index(batch_op.f('ix_terminy_ical_uid'))
        batch_op.drop_index(batch_op.f('ix_terminy_data'))

    op.drop_table('terminy')
    op.drop_table('stoliki_historia')
    with op.batch_alter_table('stanowiska', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stanowiska_id'))

    op.drop_table('stanowiska')
    op.drop_table('stan_stolow')
    with op.batch_alter_table('sprzatanie_korekty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprzatanie_korekty_id'))

    op.drop_table('sprzatanie_korekty')
    with op.batch_alter_table('rozliczenia_dnia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rozliczenia_dnia_id'))
        batch_op.drop_index(batch_op.f('ix_rozliczenia_dnia_data'))

    op.drop_table('rozliczenia_dnia')
    with op.batch_alter_table('publikacje_grafiku', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publikacje_grafiku_id'))

    op.drop_table('publikacje_grafiku')
    with op.batch_alter_table('pracownicy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pracownicy_id'))

    op.drop_table('pracownicy')
    with op.batch_alter_table('imprezy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imprezy_klient'))
        batch_op.drop_index(batch_op.f('ix_imprezy_id'))
        batch_op.drop_index(batch_op.f('ix_imprezy_data'))

    op.drop_table('imprezy')
    # ### end Alembic commands ###
